# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.0
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Set up node and yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          curl -sL https://deb.nodesource.com/setup_12.x | bash -
          apt install -y nodejs yarn
      - name: Build and setup
        run: |
          bundle install
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Test with Rspec
        run: |
          bundle exec rspec
    # test:
    #   name: Run RSpec
    #   runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v1
    #   - name: Set up Ruby 2.7
    #     uses: ruby/setup-ruby@v1
    #     with:
    #       ruby-version: 2.7.0
    #   - name: Setup YARN and NodeJS
    #     run: |
    #       sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    #       sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    #       sudo curl -sL https://deb.nodesource.com/setup_12.x | bash -
    #       sudo apt install -y nodejs yarn
    #   - name: Build and setup
    #     run: |
    #       bundle install --jobs 4 --retry 3
    #       bundle exec rails yarn:install db:setup assets:precompile
    # bundle -j 4
    # bin/rails yarn:install db:setup assets:precompile
